services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    command: ["php-fpm"]


  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend   # можно оставить как есть, образ с node нам подходит
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      VITE_API_URL: http://nginx_server/api
    command: sh -lc "npm ci || npm i && npm run dev -- --host 0.0.0.0 --port 5173"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql

volumes:
  db_data:
