services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    expose:
      - "9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    command: ["php-fpm"]

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./frontend/dist:/var/www/frontend
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
